<?php

define('NOCAPTCHA_SECRET', '6LfXeXMUAAAAAJnH6K1dXv5vjEvMeEFZKF-NGxS1');
define('NOCAPTCHA_SITEKEY', '6LfXeXMUAAAAAEiUxTkypJ4MxcuKHZX1brS9H6l2');


//define('CLOUD_MESSAGE_LEGACY_KEY','AIzaSyDiKqIHnLtqffVbNTVQ0CtQmVRyT7jP9DI'); //for local
define('CLOUD_MESSAGE_LEGACY_KEY', 'AIzaSyDY9FgdQKH4nvncjIq8Av891y5mGHiLitY'); // for staging
//define('CLOUD_MESSAGE_LEGACY_KEY','AIzaSyAW3sRmumELYIcrKTW_FxyzfyIvfBieDg8'); // for live
define('PYTHON_API_URL', 'http://34.73.221.111/gps');
define('MOBILE_APP_VERSION_CODE', 58);

/**Firebase Notification
 * cases for
 * App Side */

// NOTIFICATION_CASE_ORDER = "1";
// NOTIFICATION_CASE_LEAVE = "2";
// NOTIFICATION_CASE_COLLECTION = "3";
// NOTIFICATION_CASE_LOGOUT = "4";
// NOTIFICATION_CASE_HANDLING_DATA = "5";
// NOTIFICATION_CASE_ANNOUNCEMENT = "6";
// NOTIFICATION_CASE_EXPENSE = "7";
// NOTIFICATION_CASE_PRODUCTS = "8";
// NOTIFICATION_CASE_TASK = "9";
// NOTIFICATION_CASE_CLIENTS = "10";
// NOTIFICATION_CASE_HOLIDAY = "11";
// NOTIFICATION_CASE_COMPANY_SETTING = "12";
// NOTIFICATION_CASE_BEAT = "13";
// NOTIFICATION_CASE_BEATPLAN = "14"
// NOTIFICATION_CASE_ACTIVITY_TYPE = "15";
// NOTIFICATION_CASE_ACTIVITY_PRIORITY = "16";
// NOTIFICATION_CASE_ACTIVITY = "17";
// NOTIFICATION_CASE_TOUR_PLAN = "18";
// NOTIFICATION_CASE_NOTE = "19";
// NOTIFICATION_CASE_LEAVE_TYPE = "20";
// NOTIFICATION_CASE_RETURN_REASON = "21";
// NOTIFICATION_CASE_PARTY_TYPE = "22";
// NOTIFICATION_CASE_COLLATERAL_FOLDER = "23";
// NOTIFICATION_CASE_COLLATERAL_FILE = "24";
// NOTIFICATION_CASE_ORDER_STATUS = "25";
// NOTIFICATION_CASE_TRANSFER_CLIENTS = "26";
// NOTIFICATION_CASE_PERMISSIONS = "27";
// NOTIFICATION_CASE_EMPLOYEE_ROLE = "28";
// NOTIFICATION_CASE_BUSSINESS_TYPE = "29";
// NOTIFICATION_CASE_TAX = "30";
// NOTIFICATION_CASE_SUBSCRIPTION_LOGOUT = "31";
// NOTIFICATION_CASE_SCHEMES = "32";
// NOTIFICATION_CASE_EXPENSE_TYPE = "33";
// NOTIFICATION_CASE_CUSTOM_FIELDS = "34";
// NOTIFICATION_CASE_REMARK = "35";
// NOTIFICATION_ZERO_ORDER = "36";
// NOTIFICATION_CASE_PARTY_RATES = "37";
// NOTIFICATION_CASE_IMPORT = "38";
// NOTIFICATION_CASE_BANK = "39";
// NOTIFICATION_CASE_EMPLOYEE="40";
// NOTIFICATION_CASE_VISIT_PURPOSE="41";
// NOTIFICATION_CASE_FILES_IMAGES="42";
// NOTIFICATION_CASE_ODOMETER_REPORT="44"
// NOTIFICATION_CASE_CUSTOM_MODULE = "45"
// NOTIFICATION_CASE_CATEGORY_PRICING = "46"
?>